#!/usr/bin/env python

import socket, time, bot, sys, argparse
from threading import Timer



TIME=0 #Timer time.


def incrementtime():
    global TIME
    TIME=TIME+1
    t = Timer(1.0, incrementtime)
    t.start()


def main():
    parser = argparse.ArgumentParser(description='Runs Redditron.')
    parser.add_argument('--verbose','-v',action='store_true')
    args = parser.parse_args()

    incrementtime()
    bot.connect(args.verbose)
    
if __name__ == '__main__': 
   main()
